name: apptest

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: 3.13.0

dependencies:
  cupertino_icons: 1.0.5
  easy_localization: 3.0.2
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_screenutil: 5.8.4
  flutter_secure_storage: 8.0.0
  flutter_svg: 2.0.7
  get_it: 7.6.0
  go_router: 9.0.3
  google_fonts: 5.1.0
  hexcolor: 3.0.1
  injectable: 2.1.2
  json_annotation: 4.8.1
  logger: 1.4.0
  use_case: 0.1.1

dev_dependencies:
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: 2.2.1
  injectable_generator: 2.1.6

flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
